name: composite action test
on:
  push:
jobs:
    composite-action:
      needs: upload-artifact
      name: job to  test the composite action
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: ./
          id: compositeAction
          with:
            number1:4
            number2:2
        - run: echo ${{ steps.compositeAction.outputs.result }}
          
                   
